-- Season-ending rosters + keeper eligibility for the 2025-26 season,
-- entered from the league's roster/keeper screenshots. Safe to run once.

insert into roster_entries (season_id, owner_id, player_name, keeper_eligible, keeper_round, is_free_agent, sort_order)
select (select id from seasons where year = '2025-26'), o.id, v.player_name, v.keeper_eligible, v.keeper_round, v.is_free_agent, v.sort_order
from (values
  ('chris-blanco', 'Joe Burrow', true, 5, false, 0),
  ('chris-blanco', 'Rashee Rice', true, 4, false, 1),
  ('chris-blanco', 'Amon-Ra St. Brown', true, 1, false, 2),
  ('chris-blanco', 'James Cook III', false, null, false, 3),
  ('chris-blanco', 'Rico Dowdle', true, 6, true, 4),
  ('chris-blanco', 'George Kittle', true, 7, false, 5),
  ('chris-blanco', 'Rhamondre Stevenson', true, 6, false, 6),
  ('chris-blanco', 'Devin Singletary', false, null, false, 7),
  ('chris-blanco', 'Jayden Reed', true, 9, false, 8),
  ('chris-blanco', 'Quentin Johnston', true, 6, true, 9),
  ('chris-blanco', 'Jayden Higgins', true, 9, false, 10),
  ('chris-blanco', 'Oronde Gadsden', true, 6, true, 11),
  ('chris-blanco', 'Isaac TeSlaa', false, null, false, 12),
  ('chris-blanco', 'Parker Washington', true, 6, true, 13),
  ('kevin-blanco', 'Jalen Hurts', true, 3, false, 0),
  ('kevin-blanco', 'Jordan Addison', true, 6, false, 1),
  ('kevin-blanco', 'Cooper Kupp', false, null, false, 2),
  ('kevin-blanco', 'Jonathan Taylor', false, null, false, 3),
  ('kevin-blanco', 'Josh Jacobs', false, null, false, 4),
  ('kevin-blanco', 'Cade Otton', true, 6, true, 5),
  ('kevin-blanco', 'Keon Coleman', true, 7, false, 6),
  ('kevin-blanco', 'Malik Washington', false, null, false, 7),
  ('kevin-blanco', 'Rome Odunze', true, 6, false, 8),
  ('kevin-blanco', 'Tyjae Spears', true, 8, false, 9),
  ('kevin-blanco', 'Kayshon Boutte', true, 6, true, 10),
  ('kevin-blanco', 'Justice Hill', true, 6, true, 11),
  ('kevin-blanco', 'Sam Darnold', true, 6, true, 12),
  ('kevin-blanco', 'Sam LaPorta', true, 5, false, 13),
  ('adam-gladstone', 'Patrick Mahomes', true, 3, false, 0),
  ('adam-gladstone', 'Chris Olave', true, 8, false, 1),
  ('adam-gladstone', 'A.J. Brown', false, null, false, 2),
  ('adam-gladstone', 'David Montgomery', true, 4, false, 3),
  ('adam-gladstone', 'Kimani Vidal', true, 16, false, 4),
  ('adam-gladstone', 'Theo Johnson', true, 14, false, 5),
  ('adam-gladstone', 'Josh Downs', true, 6, true, 6),
  ('adam-gladstone', 'Jerry Jeudy', true, 7, false, 7),
  ('adam-gladstone', 'Brian Robinson', true, 6, false, 8),
  ('adam-gladstone', 'Chimere Dike', true, 6, true, 9),
  ('adam-gladstone', 'Isiah Pacheco', true, 5, false, 10),
  ('adam-gladstone', 'Brandon Aiyuk', true, 11, false, 11),
  ('adam-gladstone', 'DeVonta Smith', true, 5, false, 12),
  ('adam-gladstone', 'Najee Harris', true, 9, false, 13),
  ('chris-moreschi', 'Jared Goff', true, 12, false, 0),
  ('chris-moreschi', 'Jaxon Smith-Njigba', true, 3, false, 1),
  ('chris-moreschi', 'Puka Nacua', false, null, false, 2),
  ('chris-moreschi', 'Derrick Henry', false, null, false, 3),
  ('chris-moreschi', 'Kenny Gainwell', false, null, false, 4),
  ('chris-moreschi', 'Jake Ferguson', true, 15, false, 5),
  ('chris-moreschi', 'Xavier Worthy', true, 4, false, 6),
  ('chris-moreschi', 'Tyler Allgeier', true, 6, true, 7),
  ('chris-moreschi', 'Brock Bowers', true, 4, false, 8),
  ('chris-moreschi', 'Kyle Monangai', true, 12, false, 9),
  ('chris-moreschi', 'Jaxson Dart', true, 6, true, 10),
  ('chris-moreschi', 'Dylan Sampson', false, null, false, 11),
  ('chris-moreschi', 'Bhayshul Tuten', false, null, false, 12),
  ('chris-moreschi', 'Cam Skattebo', true, 8, false, 13),
  ('rob-moreschi', 'Bo Nix', true, 6, true, 0),
  ('rob-moreschi', 'Brian Thomas Jr.', true, 5, false, 1),
  ('rob-moreschi', 'Tee Higgins', false, null, false, 2),
  ('rob-moreschi', 'Jacory Croskey-Merritt', true, 13, false, 3),
  ('rob-moreschi', 'Alvin Kamara', true, 3, false, 4),
  ('rob-moreschi', 'Dallas Goedert', true, 11, false, 5),
  ('rob-moreschi', 'Darius Slayton', true, 6, true, 6),
  ('rob-moreschi', 'Tre Tucker', true, 6, true, 7),
  ('rob-moreschi', 'Nick Chubb', true, 6, true, 8),
  ('rob-moreschi', 'Devin Neal', false, null, false, 9),
  ('rob-moreschi', 'Kareem Hunt', true, 6, true, 10),
  ('rob-moreschi', 'T.J. Hockenson', true, 6, false, 11),
  ('rob-moreschi', 'Jayden Daniels', true, 2, false, 12),
  ('rob-moreschi', 'Travis Hunter', true, 5, false, 13),
  ('rob-moreschi', 'Tucker Kraft', true, 10, false, 14),
  ('ian-oloughlin', 'Dak Prescott', true, 8, false, 0),
  ('ian-oloughlin', 'Ladd McConkey', true, 6, false, 1),
  ('ian-oloughlin', 'Michael Wilson', false, null, false, 2),
  ('ian-oloughlin', 'Kyren Williams', true, 10, false, 3),
  ('ian-oloughlin', 'Tony Pollard', true, 6, false, 4),
  ('ian-oloughlin', 'Mark Andrews', true, 7, false, 5),
  ('ian-oloughlin', 'Jauan Jennings', true, 7, false, 6),
  ('ian-oloughlin', 'Jakobi Meyers', true, 7, false, 7),
  ('ian-oloughlin', 'Troy Franklin', true, 6, true, 8),
  ('ian-oloughlin', 'Deebo Samuel', true, 8, false, 9),
  ('ian-oloughlin', 'Darnell Mooney', true, 12, false, 10),
  ('ian-oloughlin', 'Kyle Pitts Sr.', true, 11, false, 11),
  ('ian-oloughlin', 'DJ Giddens', true, 13, false, 12),
  ('ian-oloughlin', 'Rachaad White', true, 9, false, 13),
  ('ian-oloughlin', 'Jalen McMillan', true, 13, false, 14),
  ('frank-panico', 'Trevor Lawrence', true, 6, true, 0),
  ('frank-panico', 'Zay Flowers', true, 4, false, 1),
  ('frank-panico', 'Romeo Doubs', true, 13, false, 2),
  ('frank-panico', 'Jahmyr Gibbs', false, null, false, 3),
  ('frank-panico', 'Tyrone Tracy Jr.', true, 5, false, 4),
  ('frank-panico', 'Hunter Henry', true, 16, false, 5),
  ('frank-panico', 'Jameson Williams', true, 9, false, 6),
  ('frank-panico', 'Khalil Shakir', true, 6, false, 7),
  ('frank-panico', 'Davante Adams', false, null, false, 8),
  ('frank-panico', 'Jordan Mason', true, 8, false, 9),
  ('frank-panico', 'Baker Mayfield', true, 7, false, 10),
  ('frank-panico', 'Dalton Kincaid', true, 11, false, 11),
  ('frank-panico', 'Zach Ertz', false, null, false, 12),
  ('michael-pateiro', 'Josh Allen', false, null, false, 0),
  ('michael-pateiro', 'Justin Jefferson', false, null, false, 1),
  ('michael-pateiro', 'Marvin Harrison Jr.', true, 3, false, 2),
  ('michael-pateiro', 'Bucky Irving', true, 5, false, 3),
  ('michael-pateiro', 'Saquon Barkley', false, null, false, 4),
  ('michael-pateiro', 'Colby Parkinson', false, null, false, 5),
  ('michael-pateiro', 'Ashton Jeanty', false, null, false, 6),
  ('michael-pateiro', 'RJ Harvey', true, 5, false, 7),
  ('michael-pateiro', 'Jaylen Waddle', true, 5, false, 8),
  ('michael-pateiro', 'Kenneth Walker III', true, 3, false, 9),
  ('michael-pateiro', 'Ricky Pearsall', true, 6, false, 10),
  ('michael-pateiro', 'Blake Corum', true, 6, true, 11),
  ('michael-pateiro', 'Chuba Hubbard', true, 3, false, 12),
  ('michael-pateiro', 'Audric Estime', false, null, false, 13),
  ('michael-pateiro', 'Garrett Wilson', true, 3, false, 14),
  ('soren-pedersen', 'Brock Purdy', true, 15, false, 0),
  ('soren-pedersen', 'Nico Collins', true, 7, false, 1),
  ('soren-pedersen', 'Mike Evans', false, null, false, 2),
  ('soren-pedersen', 'Bijan Robinson', false, null, false, 3),
  ('soren-pedersen', 'TreVeyon Henderson', true, 3, false, 4),
  ('soren-pedersen', 'Trey McBride', true, 2, false, 5),
  ('soren-pedersen', 'Jaylen Warren', true, 6, false, 6),
  ('soren-pedersen', 'Harold Fannin Jr.', true, 6, true, 7),
  ('soren-pedersen', 'Justin Herbert', true, 6, true, 8),
  ('soren-pedersen', 'DK Metcalf', true, 4, false, 9),
  ('soren-pedersen', 'Woody Marks', true, 6, true, 10),
  ('soren-pedersen', 'Emeka Egbuka', true, 7, false, 11),
  ('soren-pedersen', 'Keenan Allen', true, 8, false, 12),
  ('soren-pedersen', 'Ollie Gordon II', true, 6, true, 13),
  ('cuyler-peragallo', 'Lamar Jackson', false, null, false, 0),
  ('cuyler-peragallo', 'Chris Godwin Jr.', true, 10, false, 1),
  ('cuyler-peragallo', 'CeeDee Lamb', false, null, false, 2),
  ('cuyler-peragallo', 'D''Andre Swift', true, 4, false, 3),
  ('cuyler-peragallo', 'Javonte Williams', true, 6, false, 4),
  ('cuyler-peragallo', 'Travis Kelce', true, 8, false, 5),
  ('cuyler-peragallo', 'Breece Hall', true, 3, false, 6),
  ('cuyler-peragallo', 'Stefon Diggs', true, 7, false, 7),
  ('cuyler-peragallo', 'Evan Engram', true, 10, false, 8),
  ('cuyler-peragallo', 'Wan''Dale Robinson', true, 12, false, 9),
  ('cuyler-peragallo', 'Caleb Williams', true, 6, true, 10),
  ('cuyler-peragallo', 'Jordan Love', true, 6, true, 11),
  ('cuyler-peragallo', 'Hollywood Brown', true, 11, false, 12),
  ('cuyler-peragallo', 'Tyreek Hill', false, null, false, 13),
  ('jeff-peragallo', 'Matthew Stafford', true, 6, true, 0),
  ('jeff-peragallo', 'Christian Watson', true, 6, true, 1),
  ('jeff-peragallo', 'Tetairoa McMillan', true, 3, false, 2),
  ('jeff-peragallo', 'Travis Etienne Jr.', true, 6, false, 3),
  ('jeff-peragallo', 'Zach Charbonnet', true, 9, false, 4),
  ('jeff-peragallo', 'Tyler Warren', true, 8, false, 5),
  ('jeff-peragallo', 'Quinshon Judkins', true, 7, false, 6),
  ('jeff-peragallo', 'Terry McLaurin', true, 1, false, 7),
  ('jeff-peragallo', 'Alec Pierce', true, 6, true, 8),
  ('jeff-peragallo', 'Samaje Perine', true, 6, true, 9),
  ('jeff-peragallo', 'Drake London', false, null, false, 10),
  ('jeff-peragallo', 'Pat Freiermuth', false, null, false, 11),
  ('jeff-peragallo', 'Luther Burden III', false, null, false, 12),
  ('jeff-peragallo', 'Bam Knight', false, null, false, 13),
  ('jeff-peragallo', 'Kyler Murray', true, 9, false, 14),
  ('adam-rudin', 'Drake Maye', true, 12, false, 0),
  ('adam-rudin', 'George Pickens', true, 5, false, 1),
  ('adam-rudin', 'Courtland Sutton', true, 4, false, 2),
  ('adam-rudin', 'Chase Brown', true, 4, false, 3),
  ('adam-rudin', 'De''Von Achane', true, 3, false, 4),
  ('adam-rudin', 'Juwan Johnson', true, 6, true, 5),
  ('adam-rudin', 'Ja''Marr Chase', false, null, false, 6),
  ('adam-rudin', 'Christian McCaffrey', false, null, false, 7),
  ('adam-rudin', 'DJ Moore', true, 4, false, 8),
  ('adam-rudin', 'Darren Waller', true, 6, true, 9),
  ('adam-rudin', 'Aaron Jones Sr.', true, 4, false, 10),
  ('adam-rudin', 'Michael Pittman Jr.', true, 9, false, 11),
  ('adam-rudin', 'Omarion Hampton', false, null, false, 12),
  ('adam-rudin', 'Taysom Hill', false, null, false, 13)
) as v(owner_slug, player_name, keeper_eligible, keeper_round, is_free_agent, sort_order)
join owners o on o.slug = v.owner_slug;
