-- Historical draft results: 2025-26 season, entered from the league's
-- draft-day notes. Safe to run once on your existing Supabase project.

insert into drafts (season_id, rounds, draft_order, status, current_pick)
select
  (select id from seasons where year = '2025-26'),
  16,
  (select jsonb_agg(o.id order by t.ord)
   from unnest(array['soren-pedersen','rob-moreschi','ian-oloughlin','frank-panico','michael-pateiro','cuyler-peragallo','adam-rudin','jeff-peragallo','chris-blanco','kevin-blanco','chris-moreschi','adam-gladstone']) with ordinality as t(slug, ord)
   join owners o on o.slug = t.slug),
  'complete',
  193
where not exists (
  select 1 from drafts where season_id = (select id from seasons where year = '2025-26')
);

insert into draft_picks (draft_id, pick_number, round, pick_in_round, owner_id, player_name, is_keeper)
select d.id, v.pick_number, v.round, v.pick_in_round, o.id, v.player_name, v.is_keeper
from (values
  ('soren-pedersen', 1, 1, 1, 'Bijan Robinson', false),
  ('rob-moreschi', 1, 2, 2, 'Ja''Marr Chase', false),
  ('ian-oloughlin', 1, 3, 3, 'Saquon Barkley', false),
  ('frank-panico', 1, 4, 4, 'Jahmyr Gibbs', false),
  ('michael-pateiro', 1, 5, 5, 'Justin Jefferson', false),
  ('cuyler-peragallo', 1, 6, 6, 'CeeDee Lamb', false),
  ('adam-rudin', 1, 7, 7, 'Christian McCaffrey', false),
  ('jeff-peragallo', 1, 8, 8, 'Malik Nabers', false),
  ('chris-blanco', 1, 9, 9, 'Amon-Ra St. Brown', false),
  ('kevin-blanco', 1, 10, 10, 'Josh Jacobs', false),
  ('chris-moreschi', 1, 11, 11, 'Puka Nacua', false),
  ('adam-gladstone', 1, 12, 12, 'Ashton Jeanty', false),
  ('soren-pedersen', 2, 12, 24, 'Mike Evans', false),
  ('rob-moreschi', 2, 11, 23, 'Jayden Daniels', false),
  ('ian-oloughlin', 2, 10, 22, 'Lamar Jackson', false),
  ('frank-panico', 2, 9, 21, 'Davante Adams', false),
  ('michael-pateiro', 2, 8, 20, 'Josh Allen', false),
  ('cuyler-peragallo', 2, 7, 19, 'Tyreek Hill', false),
  ('adam-rudin', 2, 6, 18, 'Omarion Hampton', false),
  ('jeff-peragallo', 2, 5, 17, 'Drake London', false),
  ('chris-blanco', 2, 4, 16, 'James Cook', false),
  ('kevin-blanco', 2, 3, 15, 'Jonathan Taylor', false),
  ('chris-moreschi', 2, 2, 14, 'Derrick Henry', false),
  ('adam-gladstone', 2, 1, 13, 'A.J. Brown', false),
  ('soren-pedersen', 3, 1, 25, 'Tyjuan Henderson', false),
  ('rob-moreschi', 3, 2, 26, 'Tee Higgins', true),
  ('ian-oloughlin', 3, 3, 27, 'Kenneth Walker III', false),
  ('frank-panico', 3, 4, 28, 'Garrett Wilson', false),
  ('michael-pateiro', 3, 5, 29, 'Marvin Harrison Jr.', false),
  ('cuyler-peragallo', 3, 6, 30, 'Breece Hall', false),
  ('adam-rudin', 3, 7, 31, 'Alvin Kamara', false),
  ('jeff-peragallo', 3, 8, 32, 'Tetairoa McMillan', false),
  ('chris-blanco', 3, 9, 33, 'Chuba Hubbard', false),
  ('kevin-blanco', 3, 10, 34, 'Jalen Hurts', false),
  ('chris-moreschi', 3, 11, 35, 'James Conner', false),
  ('adam-gladstone', 3, 12, 36, 'Patrick Mahomes', false),
  ('soren-pedersen', 4, 12, 48, 'DK Metcalf', false),
  ('rob-moreschi', 4, 11, 47, 'Aaron Jones', false),
  ('ian-oloughlin', 4, 10, 46, 'Calvin Ridley', false),
  ('frank-panico', 4, 9, 45, 'Zay Flowers', false),
  ('michael-pateiro', 4, 8, 44, 'DJ Moore', false),
  ('cuyler-peragallo', 4, 7, 43, 'D''Andre Swift', false),
  ('adam-rudin', 4, 6, 42, 'Courtland Sutton', false),
  ('jeff-peragallo', 4, 5, 41, 'Terry McLaurin', true),
  ('chris-blanco', 4, 4, 40, 'Rashee Rice', false),
  ('kevin-blanco', 4, 3, 39, 'Joe Mixon', false),
  ('chris-moreschi', 4, 2, 38, 'Xavier Worthy', false),
  ('adam-gladstone', 4, 1, 37, 'David Montgomery', false),
  ('soren-pedersen', 5, 1, 49, 'Trey McBride', true),
  ('rob-moreschi', 5, 2, 50, 'Travis Hunter', false),
  ('ian-oloughlin', 5, 3, 51, 'DeVonta Smith', false),
  ('frank-panico', 5, 4, 52, 'Tyrone Tracy Jr.', false),
  ('michael-pateiro', 5, 5, 53, 'RJ Harvey', false),
  ('cuyler-peragallo', 5, 6, 54, 'Jaylen Waddle', false),
  ('adam-rudin', 5, 7, 55, 'George Pickens', false),
  ('jeff-peragallo', 5, 8, 56, 'Kaleb Johnson', false),
  ('chris-blanco', 5, 9, 57, 'Matthew Golden', false),
  ('kevin-blanco', 5, 10, 58, 'Sam LaPorta', false),
  ('chris-moreschi', 5, 11, 59, 'JK Dobbins', false),
  ('adam-gladstone', 5, 12, 60, 'Isiah Pacheco', false),
  ('soren-pedersen', 6, 12, 72, 'Jaylen Warren', false),
  ('rob-moreschi', 6, 11, 71, 'TJ Hockenson', false),
  ('ian-oloughlin', 6, 10, 70, 'Tony Pollard', false),
  ('frank-panico', 6, 9, 69, 'Khalil Shakir', false),
  ('michael-pateiro', 6, 8, 68, 'Ricky Pearsall', false),
  ('cuyler-peragallo', 6, 7, 67, 'Javonte Williams', false),
  ('adam-rudin', 6, 6, 66, 'Achane', true),
  ('jeff-peragallo', 6, 5, 65, 'Travis Etienne', false),
  ('chris-blanco', 6, 4, 64, 'Rhamondre Stevenson', false),
  ('kevin-blanco', 6, 3, 63, 'Rome Odunze', false),
  ('chris-moreschi', 6, 2, 62, 'Njigba', true),
  ('adam-gladstone', 6, 1, 61, 'Brian Robinson Jr.', false),
  ('soren-pedersen', 7, 1, 73, 'Emeka Egbuka', false),
  ('rob-moreschi', 7, 2, 74, 'Chase Brown', true),
  ('ian-oloughlin', 7, 3, 75, 'Jakobi Meyers', false),
  ('frank-panico', 7, 4, 76, 'Baker Mayfield', false),
  ('michael-pateiro', 7, 5, 77, 'Jauan Jennings', false),
  ('cuyler-peragallo', 7, 6, 78, 'Stefon Diggs', false),
  ('adam-rudin', 7, 7, 79, 'Bo Nix', false),
  ('jeff-peragallo', 7, 8, 80, 'Quinshon Judkins', false),
  ('chris-blanco', 7, 9, 81, 'Kittle', true),
  ('kevin-blanco', 7, 10, 82, 'Keon Coleman', false),
  ('chris-moreschi', 7, 11, 83, 'Bowers', true),
  ('adam-gladstone', 7, 12, 84, 'Mark Andrews', false),
  ('soren-pedersen', 8, 12, 96, 'Dak Prescott', false),
  ('rob-moreschi', 8, 11, 95, 'Keenan Allen', false),
  ('ian-oloughlin', 8, 10, 94, 'Deebo Samuel', false),
  ('frank-panico', 8, 9, 93, 'Jordan Mason', false),
  ('michael-pateiro', 8, 8, 92, 'Bucky Irving', true),
  ('cuyler-peragallo', 8, 7, 91, 'Travis Kelce', false),
  ('adam-rudin', 8, 6, 90, 'BTJ', true),
  ('jeff-peragallo', 8, 5, 89, 'Tyler Warren', false),
  ('chris-blanco', 8, 4, 88, 'Burrow', true),
  ('kevin-blanco', 8, 3, 87, 'Tyjae Spears', false),
  ('chris-moreschi', 8, 2, 86, 'Skattebo', false),
  ('adam-gladstone', 8, 1, 85, 'Chris Olave', false),
  ('soren-pedersen', 9, 1, 97, 'Josh Downs', false),
  ('rob-moreschi', 9, 2, 98, 'Michael Pittman Jr.', false),
  ('ian-oloughlin', 9, 3, 99, 'Ladd McConkey', true),
  ('frank-panico', 9, 4, 100, 'Jameson Williams', true),
  ('michael-pateiro', 9, 5, 101, 'Rachaad White', false),
  ('cuyler-peragallo', 9, 6, 102, 'Jerome Ford', false),
  ('adam-rudin', 9, 7, 103, 'Cooper Kupp', false),
  ('jeff-peragallo', 9, 8, 104, 'Zach Charbonnet', false),
  ('chris-blanco', 9, 9, 105, 'Jayden Reed', false),
  ('kevin-blanco', 9, 10, 106, 'Addison', true),
  ('chris-moreschi', 9, 11, 107, 'Jayden Higgins', false),
  ('adam-gladstone', 9, 12, 108, 'Najee Harris', false),
  ('soren-pedersen', 10, 12, 120, 'Nico Collins', true),
  ('rob-moreschi', 10, 11, 119, 'Tank Bigsby', false),
  ('ian-oloughlin', 10, 10, 118, 'David Njoku', false),
  ('frank-panico', 10, 9, 117, 'Jaydon Blue', false),
  ('michael-pateiro', 10, 8, 116, 'Brandon Aiyuk', false),
  ('cuyler-peragallo', 10, 7, 115, 'Chris Godwin', false),
  ('adam-rudin', 10, 6, 114, 'Tucker Kraft', false),
  ('jeff-peragallo', 10, 5, 113, 'Evan Engram', false),
  ('chris-blanco', 10, 4, 112, 'Jaylen Wright', false),
  ('kevin-blanco', 10, 3, 111, 'Jake Bates', false),
  ('chris-moreschi', 10, 2, 110, 'Trey Benson', false),
  ('adam-gladstone', 10, 1, 109, 'Jerry Jeudy', true),
  ('soren-pedersen', 11, 1, 121, 'Ray Davis', false),
  ('rob-moreschi', 11, 2, 122, 'Dallas Goedert', false),
  ('ian-oloughlin', 11, 3, 123, 'Austin Ekeler', false),
  ('frank-panico', 11, 4, 124, 'Dalton Kincaid', false),
  ('michael-pateiro', 11, 5, 125, 'Justin Fields', false),
  ('cuyler-peragallo', 11, 6, 126, 'Marquise Brown', false),
  ('adam-rudin', 11, 7, 127, 'Kyle Pitts', false),
  ('jeff-peragallo', 11, 8, 128, 'Bhayshul Tuten', false),
  ('chris-blanco', 11, 9, 129, 'Colston Loveland', false),
  ('kevin-blanco', 11, 10, 130, 'Braelon Allen', true),
  ('chris-moreschi', 11, 11, 131, 'Kyle Williams', false),
  ('adam-gladstone', 11, 12, 132, 'Will Shipley', false),
  ('soren-pedersen', 12, 12, 144, 'Kyle Monangai', false),
  ('rob-moreschi', 12, 11, 143, 'Xavier Legette', false),
  ('ian-oloughlin', 12, 10, 142, 'Darnell Mooney', false),
  ('frank-panico', 12, 9, 141, 'Christian Kirk', false),
  ('michael-pateiro', 12, 8, 140, 'Isaac Guerendo', false),
  ('cuyler-peragallo', 12, 7, 139, 'Tua Tagovailoa', false),
  ('adam-rudin', 12, 6, 138, 'Drake Maye', false),
  ('jeff-peragallo', 12, 5, 137, 'Kyler Murray', true),
  ('chris-blanco', 12, 4, 136, 'Dicker the Kicker', false),
  ('kevin-blanco', 12, 3, 135, 'Jack Bech', false),
  ('chris-moreschi', 12, 2, 134, 'Jared Goff', false),
  ('adam-gladstone', 12, 1, 133, 'Adam Thielen', false),
  ('soren-pedersen', 13, 1, 145, 'Keaton Mitchell', false),
  ('rob-moreschi', 13, 2, 146, 'JJ McCarthy', false),
  ('ian-oloughlin', 13, 3, 147, 'DJ Giddens', false),
  ('frank-panico', 13, 4, 148, 'Romeo Doubs', false),
  ('michael-pateiro', 13, 5, 149, 'Kyren Williams', true),
  ('cuyler-peragallo', 13, 6, 150, 'Texans DEF', false),
  ('adam-rudin', 13, 7, 151, 'Jacory Croskey-Merritt', false),
  ('jeff-peragallo', 13, 8, 152, 'Diontae Johnson', false),
  ('chris-blanco', 13, 9, 153, 'Luther Burden III', false),
  ('kevin-blanco', 13, 10, 154, 'Dyami Brown', false),
  ('chris-moreschi', 13, 11, 155, 'Rashid Shaheed', false),
  ('adam-gladstone', 13, 12, 156, 'Broncos DEF', false),
  ('soren-pedersen', 14, 12, 168, 'Cairo Santos', false),
  ('rob-moreschi', 14, 11, 167, 'Lions DEF', false),
  ('ian-oloughlin', 14, 10, 166, 'Ravens DEF', false),
  ('frank-panico', 14, 9, 165, 'Vikings DEF', false),
  ('michael-pateiro', 14, 8, 164, 'Eagles DEF', false),
  ('cuyler-peragallo', 14, 7, 163, 'Theo Johnson', false),
  ('adam-rudin', 14, 6, 162, 'Chase McLaughlin', false),
  ('jeff-peragallo', 14, 5, 161, 'Demario Douglas', false),
  ('chris-blanco', 14, 4, 160, 'Blake Corum', false),
  ('kevin-blanco', 14, 3, 159, 'Steelers DEF', false),
  ('chris-moreschi', 14, 2, 158, 'Brashard Smith', false),
  ('adam-gladstone', 14, 1, 157, 'Brandon Aubrey', false),
  ('soren-pedersen', 15, 1, 169, 'Marvin Mims', false),
  ('rob-moreschi', 15, 2, 170, 'Rashod Bateman', false),
  ('ian-oloughlin', 15, 3, 171, 'Tyler Bass', false),
  ('frank-panico', 15, 4, 172, 'Jason Sanders', false),
  ('michael-pateiro', 15, 5, 173, 'Jake Ferguson', false),
  ('cuyler-peragallo', 15, 6, 174, 'Wan''Dale Robinson', true),
  ('adam-rudin', 15, 7, 175, 'Giants DEF', false),
  ('jeff-peragallo', 15, 8, 176, 'Bills DEF', false),
  ('chris-blanco', 15, 9, 177, 'Cam Ward', false),
  ('kevin-blanco', 15, 10, 178, 'Brock Purdy', false),
  ('chris-moreschi', 15, 11, 179, 'Buccaneers DEF', false),
  ('adam-gladstone', 15, 12, 180, 'Jalin Hyatt', false),
  ('soren-pedersen', 16, 12, 192, '49ers DEF', false),
  ('rob-moreschi', 16, 11, 191, 'Matt Gay', false),
  ('ian-oloughlin', 16, 10, 190, 'Jalen McMillan', true),
  ('frank-panico', 16, 9, 189, 'Hunter Henry', false),
  ('michael-pateiro', 16, 8, 188, 'Cameron Dicker', false),
  ('cuyler-peragallo', 16, 7, 187, 'Harrison Butker', false),
  ('adam-rudin', 16, 6, 186, 'Tory Horton', false),
  ('jeff-peragallo', 16, 5, 185, 'Younghoe Koo', false),
  ('chris-blanco', 16, 4, 184, 'Patriots DEF', false),
  ('kevin-blanco', 16, 3, 183, 'Chig Okonkwo', false),
  ('chris-moreschi', 16, 2, 182, 'Jake Elliott', false),
  ('adam-gladstone', 16, 1, 181, 'Kimani Vidal', false)
) as v(owner_slug, round, pick_in_round, pick_number, player_name, is_keeper)
join owners o on o.slug = v.owner_slug
cross join (select id from drafts where season_id = (select id from seasons where year = '2025-26')) as d;
