-- Pre-seeds the 2026-27 player pool with a starter list (~180 players),
-- ranked in a sensible order, so the draft is ready to go without anyone
-- needing to paste a list first. Safe to run once.

insert into draft_players (season_year, name, position, nfl_team, rank)
select '2026-27', v.name, nullif(v.position, ''), nullif(v.nfl_team, ''), v.rank
from (values
  ('Josh Allen', 'QB', 'BUF', 1),
  ('Lamar Jackson', 'QB', 'BAL', 2),
  ('Jayden Daniels', 'QB', 'WAS', 3),
  ('Joe Burrow', 'QB', 'CIN', 4),
  ('Patrick Mahomes', 'QB', 'KC', 5),
  ('Jalen Hurts', 'QB', 'PHI', 6),
  ('Justin Herbert', 'QB', 'LAC', 7),
  ('Drake Maye', 'QB', 'NE', 8),
  ('Bo Nix', 'QB', 'DEN', 9),
  ('Baker Mayfield', 'QB', 'TB', 10),
  ('Brock Purdy', 'QB', 'SF', 11),
  ('Jared Goff', 'QB', 'DET', 12),
  ('Dak Prescott', 'QB', 'DAL', 13),
  ('Kyler Murray', 'QB', 'ARI', 14),
  ('Trevor Lawrence', 'QB', 'JAX', 15),
  ('Matthew Stafford', 'QB', 'LAR', 16),
  ('Caleb Williams', 'QB', 'CHI', 17),
  ('Bijan Robinson', 'RB', 'ATL', 18),
  ('Jahmyr Gibbs', 'RB', 'DET', 19),
  ('Saquon Barkley', 'RB', 'PHI', 20),
  ('De''Von Achane', 'RB', 'MIA', 21),
  ('Ashton Jeanty', 'RB', 'LV', 22),
  ('Christian McCaffrey', 'RB', 'SF', 23),
  ('Derrick Henry', 'RB', 'BAL', 24),
  ('Jonathan Taylor', 'RB', 'IND', 25),
  ('Josh Jacobs', 'RB', 'GB', 26),
  ('Kenneth Walker III', 'RB', 'SEA', 27),
  ('Breece Hall', 'RB', 'NYJ', 28),
  ('James Cook III', 'RB', 'BUF', 29),
  ('Chase Brown', 'RB', 'CIN', 30),
  ('Kyren Williams', 'RB', 'LAR', 31),
  ('Alvin Kamara', 'RB', 'NO', 32),
  ('David Montgomery', 'RB', 'DET', 33),
  ('Omarion Hampton', 'RB', 'LAC', 34),
  ('TreVeyon Henderson', 'RB', 'NE', 35),
  ('RJ Harvey', 'RB', 'DEN', 36),
  ('Chuba Hubbard', 'RB', 'CAR', 37),
  ('Tony Pollard', 'RB', 'TEN', 38),
  ('Isiah Pacheco', 'RB', 'KC', 39),
  ('Bucky Irving', 'RB', 'TB', 40),
  ('Rhamondre Stevenson', 'RB', 'NE', 41),
  ('Aaron Jones Sr.', 'RB', 'MIN', 42),
  ('Javonte Williams', 'RB', 'DAL', 43),
  ('Rachaad White', 'RB', 'TB', 44),
  ('Tyrone Tracy Jr.', 'RB', 'NYG', 45),
  ('Brian Robinson Jr.', 'RB', 'WAS', 46),
  ('Najee Harris', 'RB', 'LAC', 47),
  ('Jaylen Warren', 'RB', 'PIT', 48),
  ('Tyjae Spears', 'RB', 'TEN', 49),
  ('Nick Chubb', 'RB', 'HOU', 50),
  ('Cam Skattebo', 'RB', 'NYG', 51),
  ('Ja''Marr Chase', 'WR', 'CIN', 52),
  ('Justin Jefferson', 'WR', 'MIN', 53),
  ('CeeDee Lamb', 'WR', 'DAL', 54),
  ('Amon-Ra St. Brown', 'WR', 'DET', 55),
  ('Malik Nabers', 'WR', 'NYG', 56),
  ('Puka Nacua', 'WR', 'LAR', 57),
  ('Nico Collins', 'WR', 'HOU', 58),
  ('Brian Thomas Jr.', 'WR', 'JAX', 59),
  ('A.J. Brown', 'WR', 'PHI', 60),
  ('Drake London', 'WR', 'ATL', 61),
  ('Tyreek Hill', 'WR', 'MIA', 62),
  ('Marvin Harrison Jr.', 'WR', 'ARI', 63),
  ('Terry McLaurin', 'WR', 'WAS', 64),
  ('Chris Olave', 'WR', 'NO', 65),
  ('DK Metcalf', 'WR', 'PIT', 66),
  ('Garrett Wilson', 'WR', 'NYJ', 67),
  ('DJ Moore', 'WR', 'CHI', 68),
  ('Zay Flowers', 'WR', 'BAL', 69),
  ('Mike Evans', 'WR', 'TB', 70),
  ('Davante Adams', 'WR', 'LAR', 71),
  ('Jaxon Smith-Njigba', 'WR', 'SEA', 72),
  ('Rashee Rice', 'WR', 'KC', 73),
  ('Courtland Sutton', 'WR', 'DEN', 74),
  ('Jameson Williams', 'WR', 'DET', 75),
  ('Ladd McConkey', 'WR', 'LAC', 76),
  ('Xavier Worthy', 'WR', 'KC', 77),
  ('Jordan Addison', 'WR', 'MIN', 78),
  ('Tetairoa McMillan', 'WR', 'CAR', 79),
  ('Khalil Shakir', 'WR', 'BUF', 80),
  ('Stefon Diggs', 'WR', 'NE', 81),
  ('Jayden Reed', 'WR', 'GB', 82),
  ('Jerry Jeudy', 'WR', 'CLE', 83),
  ('George Pickens', 'WR', 'DAL', 84),
  ('Keon Coleman', 'WR', 'BUF', 85),
  ('Rome Odunze', 'WR', 'CHI', 86),
  ('Deebo Samuel', 'WR', 'WAS', 87),
  ('Jaylen Waddle', 'WR', 'MIA', 88),
  ('Cooper Kupp', 'WR', 'SEA', 89),
  ('Zach Charbonnet', 'RB', 'SEA', 90),
  ('Emeka Egbuka', 'WR', 'TB', 91),
  ('Travis Hunter', 'WR', 'JAX', 92),
  ('Quinshon Judkins', 'RB', 'CLE', 93),
  ('Kaleb Johnson', 'RB', 'PIT', 94),
  ('Jayden Higgins', 'WR', 'HOU', 95),
  ('Chris Godwin Jr.', 'WR', 'TB', 96),
  ('Josh Downs', 'WR', 'IND', 97),
  ('Wan''Dale Robinson', 'WR', 'NYG', 98),
  ('Darnell Mooney', 'WR', 'ATL', 99),
  ('Hollywood Brown', 'WR', 'KC', 100),
  ('Michael Pittman Jr.', 'WR', 'IND', 101),
  ('Rashod Bateman', 'WR', 'BAL', 102),
  ('Jauan Jennings', 'WR', 'SF', 103),
  ('Jakobi Meyers', 'WR', 'LV', 104),
  ('Christian Watson', 'WR', 'GB', 105),
  ('Luther Burden III', 'WR', 'CHI', 106),
  ('Travis Kelce', 'TE', 'KC', 107),
  ('Brock Bowers', 'TE', 'LV', 108),
  ('Trey McBride', 'TE', 'ARI', 109),
  ('George Kittle', 'TE', 'SF', 110),
  ('Sam LaPorta', 'TE', 'DET', 111),
  ('Mark Andrews', 'TE', 'BAL', 112),
  ('Evan Engram', 'TE', 'DEN', 113),
  ('David Njoku', 'TE', 'CLE', 114),
  ('Dallas Goedert', 'TE', 'PHI', 115),
  ('Jonnu Smith', 'TE', 'PIT', 116),
  ('Tucker Kraft', 'TE', 'GB', 117),
  ('T.J. Hockenson', 'TE', 'MIN', 118),
  ('Colston Loveland', 'TE', 'CHI', 119),
  ('Kyle Pitts Sr.', 'TE', 'ATL', 120),
  ('Dalton Kincaid', 'TE', 'BUF', 121),
  ('Jake Ferguson', 'TE', 'DAL', 122),
  ('Theo Johnson', 'TE', 'NYG', 123),
  ('Zach Ertz', 'TE', 'WAS', 124),
  ('Cade Otton', 'TE', 'TB', 125),
  ('Tyler Warren', 'TE', 'IND', 126),
  ('Justin Tucker', 'K', 'BAL', 127),
  ('Harrison Butker', 'K', 'KC', 128),
  ('Brandon Aubrey', 'K', 'DAL', 129),
  ('Chris Boswell', 'K', 'PIT', 130),
  ('Jake Bates', 'K', 'DET', 131),
  ('Cameron Dicker', 'K', 'LAC', 132),
  ('Jason Sanders', 'K', 'MIA', 133),
  ('Younghoe Koo', 'K', 'ATL', 134),
  ('Ka''imi Fairbairn', 'K', 'HOU', 135),
  ('Baltimore Ravens', 'DEF', 'BAL', 136),
  ('San Francisco 49ers', 'DEF', 'SF', 137),
  ('Pittsburgh Steelers', 'DEF', 'PIT', 138),
  ('Denver Broncos', 'DEF', 'DEN', 139),
  ('Philadelphia Eagles', 'DEF', 'PHI', 140),
  ('Houston Texans', 'DEF', 'HOU', 141),
  ('Kansas City Chiefs', 'DEF', 'KC', 142),
  ('Buffalo Bills', 'DEF', 'BUF', 143),
  ('Minnesota Vikings', 'DEF', 'MIN', 144),
  ('Dallas Cowboys', 'DEF', 'DAL', 145)
) as v(name, position, nfl_team, rank);
